name = "ImplicitDifferentiation"
uuid = "57b37032-215b-411a-8a7c-41a003a55207"
authors = ["Guillaume Dalle", "Mohamed Tarek"]
version = "0.9.1"

[deps]
ADTypes = "47edcb42-4c32-4615-8424-f2b9edc5f35b"
DifferentiationInterface = "a0c0ee7d-e4b9-4e03-894e-1c5f64a51d63"
KrylovKit = "0b1a1467-8014-51b9-945f-bf0ae24f4b77"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[weakdeps]
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[extensions]
ImplicitDifferentiationChainRulesCoreExt = "ChainRulesCore"
ImplicitDifferentiationForwardDiffExt = "ForwardDiff"
ImplicitDifferentiationZygoteExt = "Zygote"

[compat]
ADTypes = "1.9.0"
ChainRulesCore = "1.25.0"
DifferentiationInterface = "0.6.1,0.7"
ForwardDiff = "0.10.36, 1"
KrylovKit = "0.10.0"
LinearAlgebra = "1"
Zygote = "0.7.4"
julia = "1.10"
